var annotated_dup =
[
    [ "LavaVK", null, [
      [ "Buffer", "class_lava_v_k_1_1_buffer.html", "class_lava_v_k_1_1_buffer" ],
      [ "BufferCreateInfo", "struct_lava_v_k_1_1_buffer_create_info.html", "struct_lava_v_k_1_1_buffer_create_info" ],
      [ "CommandBuffer", "class_lava_v_k_1_1_command_buffer.html", "class_lava_v_k_1_1_command_buffer" ],
      [ "CommandPool", "class_lava_v_k_1_1_command_pool.html", "class_lava_v_k_1_1_command_pool" ],
      [ "DescriptorPool", "class_lava_v_k_1_1_descriptor_pool.html", "class_lava_v_k_1_1_descriptor_pool" ],
      [ "DescriptorSetLayout", "class_lava_v_k_1_1_descriptor_set_layout.html", "class_lava_v_k_1_1_descriptor_set_layout" ],
      [ "DescriptorSetLayoutBinding", "struct_lava_v_k_1_1_descriptor_set_layout_binding.html", "struct_lava_v_k_1_1_descriptor_set_layout_binding" ],
      [ "DescriptorWriter", "class_lava_v_k_1_1_descriptor_writer.html", "class_lava_v_k_1_1_descriptor_writer" ],
      [ "Device", "class_lava_v_k_1_1_device.html", "class_lava_v_k_1_1_device" ],
      [ "Extent2D", "struct_lava_v_k_1_1_extent2_d.html", "struct_lava_v_k_1_1_extent2_d" ],
      [ "Fence", "class_lava_v_k_1_1_fence.html", "class_lava_v_k_1_1_fence" ],
      [ "Format", "class_lava_v_k_1_1_format.html", "class_lava_v_k_1_1_format" ],
      [ "Framebuffer", "class_lava_v_k_1_1_framebuffer.html", "class_lava_v_k_1_1_framebuffer" ],
      [ "GPUHardware", "class_lava_v_k_1_1_g_p_u_hardware.html", "class_lava_v_k_1_1_g_p_u_hardware" ],
      [ "GraphicsPipeline", "class_lava_v_k_1_1_graphics_pipeline.html", "class_lava_v_k_1_1_graphics_pipeline" ],
      [ "GraphicsPipelineCreateInfo", "struct_lava_v_k_1_1_graphics_pipeline_create_info.html", "struct_lava_v_k_1_1_graphics_pipeline_create_info" ],
      [ "Image", "class_lava_v_k_1_1_image.html", "class_lava_v_k_1_1_image" ],
      [ "ImageCreateInfo", "struct_lava_v_k_1_1_image_create_info.html", "struct_lava_v_k_1_1_image_create_info" ],
      [ "Instance", "class_lava_v_k_1_1_instance.html", "class_lava_v_k_1_1_instance" ],
      [ "InstanceCreateInfo", "struct_lava_v_k_1_1_instance_create_info.html", "struct_lava_v_k_1_1_instance_create_info" ],
      [ "MemberTraits", "struct_lava_v_k_1_1_member_traits.html", null ],
      [ "MemberTraits&lt; MemberPtr &gt;", "struct_lava_v_k_1_1_member_traits_3_01_member_ptr_01_4.html", "struct_lava_v_k_1_1_member_traits_3_01_member_ptr_01_4" ],
      [ "PipelineLayout", "class_lava_v_k_1_1_pipeline_layout.html", "class_lava_v_k_1_1_pipeline_layout" ],
      [ "PushConstantRange", "struct_lava_v_k_1_1_push_constant_range.html", "struct_lava_v_k_1_1_push_constant_range" ],
      [ "Queue", "class_lava_v_k_1_1_queue.html", "class_lava_v_k_1_1_queue" ],
      [ "RenderPass", "class_lava_v_k_1_1_render_pass.html", "class_lava_v_k_1_1_render_pass" ],
      [ "Result", "struct_lava_v_k_1_1_result.html", "struct_lava_v_k_1_1_result" ],
      [ "Semaphore", "class_lava_v_k_1_1_semaphore.html", "class_lava_v_k_1_1_semaphore" ],
      [ "Shader", "class_lava_v_k_1_1_shader.html", "class_lava_v_k_1_1_shader" ],
      [ "SubmitInfo", "class_lava_v_k_1_1_submit_info.html", "class_lava_v_k_1_1_submit_info" ],
      [ "Surface", "class_lava_v_k_1_1_surface.html", "class_lava_v_k_1_1_surface" ],
      [ "SurfaceCapabilities", "struct_lava_v_k_1_1_surface_capabilities.html", "struct_lava_v_k_1_1_surface_capabilities" ],
      [ "SurfaceFormatInfo", "struct_lava_v_k_1_1_surface_format_info.html", "struct_lava_v_k_1_1_surface_format_info" ],
      [ "SwapChain", "class_lava_v_k_1_1_swap_chain.html", "class_lava_v_k_1_1_swap_chain" ],
      [ "VertexLayout", "class_lava_v_k_1_1_vertex_layout.html", "class_lava_v_k_1_1_vertex_layout" ]
    ] ]
];